[build]
  publish = "public"
  command = ""

[dev]
  publish = "public"
  command = "npx live-server public"
  targetPort = 5500
  port = 8888
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
